# Site settings
title: sandow
email: j.k.yulei@gmail.com
description: Do what you want
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  magdre
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

owner:
  name:           sandow
  avatar:         avatar.jpg
  bio:            "The only thing that never changes is that everything always changes."
  email:  


# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
