gems: [jekyll-paginate]

highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: 
devurl: http://localhost:4000/
name: SanDow
title: sandow | Another yet unique freak is showing a freakshow
description: "sandow's personal weblog, on coding or such stuff"

my:
    displayName: sandow
    realName: 
    realName_cn: "sandow"
    jobTitle: "Data Mining"
    contact:
        qq: 921070747
        email: j.k.yulei@gmail.com
        github: http://www.github.com/magdre
        qzone: http://921070747.qzone.qq.com
        pinterest: https://www.pinterest.com/jkyulei/
        tel: 18010073860
        address:
            country: China
            state: "北京"
            city: 
            distribute: "海淀"
            postcode: 10000
            cell: "上地"
    skills:
        frontend: ["Linux", "MySql | Mongodb ", "memcached | spark", "Apache | Nginx"]
        backend: ["Python | Java | matlab"  ]
        tools: ["Sublime | VIM", "Git | SVN"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
